Repository magma-hackers/finden, pull requests merged in 2018-12, with the labels that each got.

#42 Feature/header navigation fixes
  app/assets/fonts/Oxygen-Regular.ttf
  app/assets/fonts/Rubik-Regular.ttf
  app/assets/images/about-img.jpg
  app/assets/images/finden.png
  app/assets/javascripts/pages.coffee
  app/assets/settings/colors.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages.scss
  app/assets/stylesheets/welcome.scss
  app/controllers/pages_controller.rb
  app/helpers/pages_helper.rb
  app/views/layouts/application.html.erb
  app/views/pages/about.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/faq.html.erb
  app/views/welcome/_banner.html.erb
  app/views/welcome/_footer.html.erb
  app/views/welcome/_header.html.erb
  config/application.rb
  config/locales/en.yml
  config/locales/es.yml
  config/routes.rb
  test/controllers/pages_controller_test.rb
Labels: Code Review

#46 add changes to teams form feature #40
  app/assets/javascripts/pages.coffee
  app/assets/settings/colors.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/teams.scss
  app/controllers/teams_controller.rb
  app/helpers/teams_helper.rb
  app/models/team.rb
  app/views/teams/_form.html.erb
  app/views/teams/_team.json.jbuilder
  app/views/teams/edit.html.erb
  app/views/teams/index.html.erb
  app/views/teams/index.json.jbuilder
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  app/views/teams/show.json.jbuilder
  config/locales/en.yml
  config/locales/es-MX.yml
  config/locales/es.yml
  config/routes.rb
  db/migrate/20181211150157_create_teams.rb
  db/schema.rb
  test/controllers/teams_controller_test.rb
  test/fixtures/teams.yml
  test/models/team_test.rb
  test/system/teams_test.rb
Labels: Code Review, Ready for review

#45 add changes to contractual form feature #38
  app/assets/javascripts/welcome.coffee
  app/assets/stylesheets/contractuals.scss
  app/controllers/contractuals_controller.rb
  app/helpers/contractuals_helper.rb
  app/models/contractual.rb
  app/views/contractuals/_contractual.json.jbuilder
  app/views/contractuals/_form.html.erb
  app/views/contractuals/edit.html.erb
  app/views/contractuals/index.html.erb
  app/views/contractuals/index.json.jbuilder
  app/views/contractuals/new.html.erb
  app/views/contractuals/show.html.erb
  app/views/contractuals/show.json.jbuilder
  config/locales/en.yml
  config/locales/es.yml
  config/routes.rb
  db/migrate/20181211145433_create_contractuals.rb
  db/schema.rb
  test/controllers/contractuals_controller_test.rb
  test/fixtures/contractuals.yml
  test/models/contractual_test.rb
  test/system/contractuals_test.rb
Labels: Code Review, Ready for review

#44 add changes to technique form feature #39
  app/assets/stylesheets/techniques.scss
  app/controllers/techniques_controller.rb
  app/helpers/techniques_helper.rb
  app/models/technique.rb
  app/views/techniques/_form.html.erb
  app/views/techniques/_technique.json.jbuilder
  app/views/techniques/edit.html.erb
  app/views/techniques/index.html.erb
  app/views/techniques/index.json.jbuilder
  app/views/techniques/new.html.erb
  app/views/techniques/show.html.erb
  app/views/techniques/show.json.jbuilder
  config/locales/en.yml
  config/locales/es.yml
  config/routes.rb
  db/migrate/20181211150002_create_techniques.rb
  db/migrate/20181219191346_change_technique_column_name.rb
  db/schema.rb
  test/controllers/techniques_controller_test.rb
  test/fixtures/techniques.yml
  test/models/technique_test.rb
  test/system/techniques_test.rb
Labels: Code Review, Ready for review

#53 Add cancan gem to role users #43
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/ability.rb
  app/views/teams/index.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/routes.rb
  db/migrate/20181219174649_add_role_to_users.rb
  db/schema.rb
Labels: Code Review

#55 add Enhancement to the form ticket #48
  app/views/teams/_form.html.erb
  app/views/teams/edit.html.erb
  app/views/teams/index.html.erb
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  config/locales/en.yml
  config/locales/es.yml
Labels: Code Review

#56 Fix from cancanGEM #57
  config/routes.rb
  db/migrate/20181219191346_change_technique_column_name.rb
  db/schema.rb
Labels: Code Review, bug

#58 form style enhancement ticket #50
  app/views/contractuals/_form.html.erb
  app/views/contractuals/edit.html.erb
  app/views/contractuals/index.html.erb
  app/views/contractuals/new.html.erb
  app/views/contractuals/show.html.erb
  app/views/teams/_form.html.erb
  app/views/teams/edit.html.erb
  app/views/teams/index.html.erb
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  app/views/techniques/_form.html.erb
  app/views/techniques/edit.html.erb
  app/views/techniques/index.html.erb
  app/views/techniques/new.html.erb
  app/views/techniques/show.html.erb
Labels: Code Review

#59 adding changes to detect visor or player
  app/controllers/application_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/ability.rb
  app/models/team.rb
  app/views/devise/registrations/new.html.erb
  config/initializers/devise.rb
Labels: Code Review, Ready for review
